import type { Food } from './foods';

// Drink case: approximate prices in thousands of VND for one cup. No artwork — cards show a cup icon.
type DrinkRow=[name:string,nameEn:string,sub:string,price:number];
const rows:DrinkRow[]=[
 ["Trà sữa trân châu", "Bubble milk tea", "Trà sữa", 35],
 ["Trà sữa matcha", "Matcha milk tea", "Trà sữa", 40],
 ["Trà sữa khoai môn", "Taro milk tea", "Trà sữa", 40],
 ["Sữa tươi trân châu đường đen", "Brown sugar boba milk", "Trà sữa", 45],
 ["Trà sữa ô long", "Oolong milk tea", "Trà sữa", 45],
 ["Trà sữa kem cheese", "Cheese foam milk tea", "Trà sữa", 50],
 ["Cà phê đen đá", "Iced black coffee", "Cà phê", 20],
 ["Cà phê sữa đá", "Iced milk coffee", "Cà phê", 25],
 ["Bạc xỉu", "Bac xiu (milky coffee)", "Cà phê", 28],
 ["Cà phê muối", "Salted cream coffee", "Cà phê", 35],
 ["Cà phê trứng", "Egg coffee", "Cà phê", 40],
 ["Cà phê cốt dừa", "Coconut coffee", "Cà phê", 40],
 ["Latte", "Latte", "Cà phê", 55],
 ["Cappuccino", "Cappuccino", "Cà phê", 55],
 ["Cold brew", "Cold brew", "Cà phê", 60],
 ["Trà đá", "Iced tea", "Trà", 5],
 ["Trà chanh", "Lime iced tea", "Trà", 15],
 ["Trà tắc", "Kumquat tea", "Trà", 18],
 ["Trà đào cam sả", "Peach lemongrass tea", "Trà", 45],
 ["Trà vải", "Lychee tea", "Trà", 40],
 ["Trà ô long sen", "Lotus oolong tea", "Trà", 45],
 ["Trà xanh macchiato", "Green tea macchiato", "Trà", 50],
 ["Trà dâu tằm", "Mulberry tea", "Trà", 40],
 ["Nước mía", "Sugarcane juice", "Giải khát", 15],
 ["Nước dừa tươi", "Fresh coconut water", "Giải khát", 30],
 ["Sâm bí đao", "Winter melon tea", "Giải khát", 15],
 ["Rau má đậu xanh", "Pennywort mung bean drink", "Giải khát", 25],
 ["Chè khúc bạch", "Khuc bach sweet soup", "Giải khát", 35],
 ["Sữa đậu nành", "Soy milk", "Giải khát", 15],
 ["Tàu hũ trân châu", "Tofu pudding with boba", "Giải khát", 25],
 ["Nước cam", "Orange juice", "Nước ép", 35],
 ["Nước ép dưa hấu", "Watermelon juice", "Nước ép", 30],
 ["Nước ép ổi", "Guava juice", "Nước ép", 30],
 ["Nước ép thơm", "Pineapple juice", "Nước ép", 30],
 ["Nước ép cần tây", "Celery juice", "Nước ép", 45],
 ["Chanh dây đá", "Passion fruit soda", "Nước ép", 25],
 ["Sinh tố bơ", "Avocado smoothie", "Sinh tố", 45],
 ["Sinh tố xoài", "Mango smoothie", "Sinh tố", 40],
 ["Sinh tố dâu", "Strawberry smoothie", "Sinh tố", 45],
 ["Sinh tố mãng cầu", "Soursop smoothie", "Sinh tố", 40],
 ["Sữa chua đánh đá", "Iced beaten yogurt", "Sinh tố", 25],
 ["Sữa chua việt quất", "Blueberry yogurt smoothie", "Sinh tố", 50],
 ["Soda chanh", "Lime soda", "Soda", 30],
 ["Soda việt quất", "Blueberry soda", "Soda", 40],
 ["Mojito bạc hà", "Virgin mint mojito", "Soda", 50],
 ["Kombucha", "Kombucha", "Soda", 60],
 ["Matcha latte", "Matcha latte", "Đặc biệt", 60],
 ["Chocolate đá xay", "Chocolate frappé", "Đặc biệt", 65],
 ["Cookie đá xay", "Cookies & cream frappé", "Đặc biệt", 65],
 ["Trà sữa hoàng kim", "Golden royal milk tea", "Đặc biệt", 75],
];
// Drinks are cheaper than meals, so tiers use their own price bands.
export function drinkRarity(price:number){return price<=20?0:price<=35?1:price<=50?2:price<=65?3:4}
export const drinks:Food[]=rows.map(([name,nameEn,sub,price],i)=>({customId:`drink-${i}`,drink:true,name,nameEn,sub,price,rarity:drinkRarity(price),image:-1,quip:''}));
