// Static image imports (e.g. `import logo from "@/public/logo.png"`). next-env.d.ts declares these, but it is generated by
// `next dev` / `next build` and gitignored, so a fresh checkout (CI's typecheck) would not know them.
declare module "*.png" {
  const content: import("next/image").StaticImageData;
  export default content;
}
declare module "*.jpg" {
  const content: import("next/image").StaticImageData;
  export default content;
}
declare module "*.webp" {
  const content: import("next/image").StaticImageData;
  export default content;
}
declare module "*.svg" {
  const content: import("next/image").StaticImageData;
  export default content;
}
