import type { PixelIcon } from "./icons";

// 16×16 icons for the twelve species (spec §11): "." transparent, "o" outline, other letters from the
// icon's own palette. Original art — distinct silhouettes per species.

export const FISH_ICONS: Record<string, PixelIcon> = {
  ca_ro: {
    rows: [
      "................",
      "................",
      "....o.o.o.o.....",
      "...ofofofofo....",
      "..obbbbbbbbbo.oo",
      ".obbbbbbbbbbbofo",
      "obkbbbbbbbbbbfFo",
      "obbbbbbbbbbsbfFo",
      "owbbbbbbbbbbbfFo",
      "owwbbbbbbbbbbfFo",
      ".owwwwwbbbbbbofo",
      "..oowwwwwwboo.oo",
      "....oooooooo....",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#7d8a3c", w: "#c9c27a", f: "#5f6b2a", F: "#4a5520", k: "#1a1410", s: "#2f3316" },
  },
  ca_sac: {
    rows: [
      "................",
      "................",
      "................",
      "....ooooooo.....",
      "..oobbbbbbboo.oo",
      ".obbsbbbsbbbbofo",
      "obkbbsbbbsbbbfFo",
      "obbbsbbbsbbbbfFo",
      "owbbbsbbbsbbbfFo",
      "owwbbbsbbbsbbfFo",
      ".owwwwwsbbbsbofo",
      "..oowwwwwbboo.oo",
      "....ooooooo.....",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#8f9d5c", w: "#dcd6a4", f: "#6a7a3e", F: "#56642f", k: "#1a1410", s: "#3e4a26" },
  },
  ca_me_vinh: {
    rows: [
      "................",
      "................",
      ".......oo.......",
      "......offo......",
      "....oobffboo..oo",
      "...obbbbbbbo.ofo",
      "..obbbbbbbbbbofo",
      ".obkbbbbbbbbbfFo",
      "obbbbbbbbbbbbfFo",
      "owbbbbbbbbbbbfFo",
      "owwbbbbbbbbbbfFo",
      ".owwwwbbbbbbbofo",
      "..owwwwwwbbbo.oo",
      "...oooffoooo....",
      ".....oo.........",
      "................",
    ],
    pal: { b: "#c3c8d4", w: "#eef0f5", f: "#e8a13a", F: "#c47a22", k: "#1a1410" },
  },
  ca_loc: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      "..oooooooooooo..",
      ".obbbbbbbbbbbboo",
      "obebbsbbbsbbbbfo",
      "obbbsssbbsssbbFo",
      "owwbbbbbbbbbbbFo",
      ".owwwwwwwwwwwbfo",
      "..ooooooooooooo.",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#5e5140", w: "#b9ad8c", f: "#4a4032", F: "#393126", e: "#f2e6c8", s: "#2b241b" },
  },
  ca_tre: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      ".....oooooooooo.",
      "o...obbbbbbbbbbo",
      ".o.obkbbbbbbbbfo",
      "..obbbbbbbbbbbFo",
      ".o.owwbbbbbbbbFo",
      "o...owwwwwwwwbfo",
      ".....oooooooooo.",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#b8913a", w: "#ead9a2", f: "#8a6a28", F: "#6e5420", k: "#1a1410" },
  },
  ca_chep: {
    rows: [
      "................",
      "................",
      ".....oooo.......",
      "....offffoo.....",
      "...obbbbbbbbo.oo",
      "..obbsbbsbbbbofo",
      ".obkbbbsbbsbbfFo",
      "obbbbsbbsbbsbbfo",
      "owbbbbbsbbsbbfFo",
      "owwwbsbbsbbbbofo",
      ".owwwwwbbbbboo.o",
      "..oowwwwwwoo....",
      "....oofooo......",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#e0a431", w: "#f6dc8c", f: "#e0662f", F: "#b84a1f", k: "#1a1410", s: "#b87a1c" },
  },
  ca_tra: {
    rows: [
      "................",
      "................",
      "................",
      ".......o........",
      "......ofo.......",
      "...ooobbbooo..oo",
      "..obbbbbbbbo.ofo",
      ".obkbbbbbbbbbofo",
      "obbbbbbbbbbbbbfo",
      "owwwbbbbbbbbbbfo",
      ".owwwwwwwwbbbofo",
      "o.oooooooooo.ofo",
      "..............oo",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#6f7a84", w: "#c9d0d6", f: "#4a535c", F: "#3a4148", k: "#101418" },
  },
  ca_that_lat: {
    rows: [
      "................",
      "................",
      "................",
      ".....ooooo......",
      "...oobbbbboo....",
      "..obbbbbbbbbo...",
      ".obkbbbbbbbbboo.",
      "obbbbbbbbbbbbbbo",
      "owwwwbbbbbbbbbbo",
      ".owwwwwwwbbbbbfo",
      "..offfffffffffo.",
      "...ooooooooooo..",
      "................",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#a89a78", w: "#e4dcc4", f: "#8a7a58", F: "#6e6044", k: "#1a1410" },
  },
  tom_cang: {
    rows: [
      "................",
      "o..............o",
      ".o..ooooo.....o.",
      "..oobbbbbooo.o..",
      "...obkbbbbbboo..",
      "..obbbbsbbsbbbo.",
      ".occobbbsbbsbbbo",
      "occco.obbbbbbbbo",
      ".oo....obbbbbbo.",
      "..........obbbo.",
      "..........offfo.",
      ".........offfo..",
      "..........ooo...",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#d98a5a", w: "#f2c49a", f: "#c96a3a", F: "#a8522a", k: "#1a1410", s: "#b86a3e", c: "#3d6fd1" },
  },
  ca_bong_lau: {
    rows: [
      "................",
      "................",
      "................",
      ".......o........",
      "......ofo.......",
      "...ooobbbooo..oo",
      "..obbbbbbbbo.ofo",
      ".obkbbbbbbbbbofo",
      "obbbbbbbbbbbbbfo",
      "owwwbbbbbbbbbbfo",
      ".owwwwwwwwbbbofo",
      "o.oooooooooo.ofo",
      "..............oo",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#b9c3c9", w: "#f0f3f4", f: "#e3c65a", F: "#b89a34", k: "#101418" },
  },
  ca_he_vang: {
    rows: [
      "................",
      "................",
      ".......oo.......",
      "......okfo......",
      "....oobffboo..oo",
      "...obbbbbbbo.ofo",
      "..obbbbbbbbbbofo",
      ".obkbbbbbbbbbfFo",
      "obbbbbbbbbbbbfFo",
      "owbbbbbbbbbbbfFo",
      "owwbbbbbbbbbbfFo",
      ".owwwwbbbbbbbofo",
      "..owwwwwwbbbo.oo",
      "...oooffoooo....",
      ".....oo.........",
      "................",
    ],
    pal: { b: "#e8c24a", w: "#f7e7a8", f: "#d8432f", F: "#a82f22", k: "#1a1410" },
  },
  ca_ho: {
    rows: [
      "................",
      "......oooo......",
      "....oobbbboo....",
      "...obbsbbsbbo..o",
      "..obbbbsbbsbo.oo",
      ".obbsbbbsbbsbofo",
      "obkbbbsbbbsbbfFo",
      "obbbbbbbsbbbsfFo",
      "owwbbsbbbsbbbfFo",
      "owwwwbbsbbbsbofo",
      ".owwwwwwbbbbo.oo",
      "..oowwwwwwwoo..o",
      "....ooooooo.....",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#8d949c", w: "#d9dde1", f: "#6a7078", F: "#50555c", k: "#101418", s: "#6e757c" },
  },
};
