import { FISH_V3_ICONS } from "./gear-v3";
import type { PixelIcon } from "./icons";

// 16×16 icons for the twelve species (spec §11): "." transparent, "o" outline, other letters from the
// icon's own palette. Original art — distinct silhouettes per species.

const BASE_FISH_ICONS: Record<string, PixelIcon> = {
  ca_ro: {
    rows: [
      "................",
      "................",
      "....o.o.o.o.....",
      "...ofofofofo....",
      "..obbbbbbbbbo.oo",
      ".obbbbbbbbbbbofo",
      "obkbbbbbbbbbbfFo",
      "obbbbbbbbbbsbfFo",
      "owbbbbbbbbbbbfFo",
      "owwbbbbbbbbbbfFo",
      ".owwwwwbbbbbbofo",
      "..oowwwwwwboo.oo",
      "....oooooooo....",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#7d8a3c", w: "#c9c27a", f: "#5f6b2a", F: "#4a5520", k: "#1a1410", s: "#2f3316" },
  },
  ca_sac: {
    rows: [
      "................",
      "................",
      "................",
      "....ooooooo.....",
      "..oobbbbbbboo.oo",
      ".obbsbbbsbbbbofo",
      "obkbbsbbbsbbbfFo",
      "obbbsbbbsbbbbfFo",
      "owbbbsbbbsbbbfFo",
      "owwbbbsbbbsbbfFo",
      ".owwwwwsbbbsbofo",
      "..oowwwwwbboo.oo",
      "....ooooooo.....",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#8f9d5c", w: "#dcd6a4", f: "#6a7a3e", F: "#56642f", k: "#1a1410", s: "#3e4a26" },
  },
  ca_me_vinh: {
    rows: [
      "................",
      "................",
      ".......oo.......",
      "......offo......",
      "....oobffboo..oo",
      "...obbbbbbbo.ofo",
      "..obbbbbbbbbbofo",
      ".obkbbbbbbbbbfFo",
      "obbbbbbbbbbbbfFo",
      "owbbbbbbbbbbbfFo",
      "owwbbbbbbbbbbfFo",
      ".owwwwbbbbbbbofo",
      "..owwwwwwbbbo.oo",
      "...oooffoooo....",
      ".....oo.........",
      "................",
    ],
    pal: { b: "#c3c8d4", w: "#eef0f5", f: "#e8a13a", F: "#c47a22", k: "#1a1410" },
  },
  ca_loc: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      "..oooooooooooo..",
      ".obbbbbbbbbbbboo",
      "obebbsbbbsbbbbfo",
      "obbbsssbbsssbbFo",
      "owwbbbbbbbbbbbFo",
      ".owwwwwwwwwwwbfo",
      "..ooooooooooooo.",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#5e5140", w: "#b9ad8c", f: "#4a4032", F: "#393126", e: "#f2e6c8", s: "#2b241b" },
  },
  ca_tre: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      ".....oooooooooo.",
      "o...obbbbbbbbbbo",
      ".o.obkbbbbbbbbfo",
      "..obbbbbbbbbbbFo",
      ".o.owwbbbbbbbbFo",
      "o...owwwwwwwwbfo",
      ".....oooooooooo.",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#b8913a", w: "#ead9a2", f: "#8a6a28", F: "#6e5420", k: "#1a1410" },
  },
  ca_chep: {
    rows: [
      "................",
      "................",
      ".....oooo.......",
      "....offffoo.....",
      "...obbbbbbbbo.oo",
      "..obbsbbsbbbbofo",
      ".obkbbbsbbsbbfFo",
      "obbbbsbbsbbsbbfo",
      "owbbbbbsbbsbbfFo",
      "owwwbsbbsbbbbofo",
      ".owwwwwbbbbboo.o",
      "..oowwwwwwoo....",
      "....oofooo......",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#e0a431", w: "#f6dc8c", f: "#e0662f", F: "#b84a1f", k: "#1a1410", s: "#b87a1c" },
  },
  ca_tra: {
    rows: [
      "................",
      "................",
      "................",
      ".......o........",
      "......ofo.......",
      "...ooobbbooo..oo",
      "..obbbbbbbbo.ofo",
      ".obkbbbbbbbbbofo",
      "obbbbbbbbbbbbbfo",
      "owwwbbbbbbbbbbfo",
      ".owwwwwwwwbbbofo",
      "o.oooooooooo.ofo",
      "..............oo",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#6f7a84", w: "#c9d0d6", f: "#4a535c", F: "#3a4148", k: "#101418" },
  },
  ca_that_lat: {
    rows: [
      "................",
      "................",
      "................",
      ".....ooooo......",
      "...oobbbbboo....",
      "..obbbbbbbbbo...",
      ".obkbbbbbbbbboo.",
      "obbbbbbbbbbbbbbo",
      "owwwwbbbbbbbbbbo",
      ".owwwwwwwbbbbbfo",
      "..offfffffffffo.",
      "...ooooooooooo..",
      "................",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#a89a78", w: "#e4dcc4", f: "#8a7a58", F: "#6e6044", k: "#1a1410" },
  },
  tom_cang: {
    rows: [
      "................",
      "o..............o",
      ".o..ooooo.....o.",
      "..oobbbbbooo.o..",
      "...obkbbbbbboo..",
      "..obbbbsbbsbbbo.",
      ".occobbbsbbsbbbo",
      "occco.obbbbbbbbo",
      ".oo....obbbbbbo.",
      "..........obbbo.",
      "..........offfo.",
      ".........offfo..",
      "..........ooo...",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#d98a5a", w: "#f2c49a", f: "#c96a3a", F: "#a8522a", k: "#1a1410", s: "#b86a3e", c: "#3d6fd1" },
  },
  ca_bong_lau: {
    rows: [
      "................",
      "................",
      ".......o......oo",
      "......ofo....ofo",
      "......ofFo..ofFo",
      "o...oooffoooffFo",
      ".o.obbbbbbbbfFo.",
      "..obkbbbbbbbfo..",
      "..obbbbbbbbbfo..",
      ".o.owwwwwwwbfFo.",
      "o...ooooffFoffFo",
      "........ooo.ofFo",
      ".............ofo",
      "..............oo",
      "................",
      "................",
    ],
    pal: { b: "#b9c3c9", w: "#f0f3f4", f: "#e3c65a", F: "#b89a34", k: "#101418" },
  },
  ca_he_vang: {
    rows: [
      "................",
      "................",
      "......o.........",
      ".....oko......oo",
      ".....ofFo....ofo",
      "...ooofFooo.ofFo",
      "..obbbbbbbboffFo",
      ".obkbbbbbbbffFo.",
      "obbbbbbbbbbfFo..",
      "owwbbbbbbbbffFo.",
      ".owwwwwwwwboffFo",
      "..oofFoofFo.ofFo",
      "....oo..oo...ofo",
      "..............oo",
      "................",
      "................",
    ],
    pal: { b: "#e8c24a", w: "#f7e7a8", f: "#d8432f", F: "#a82f22", k: "#1a1410" },
  },
  ca_ho: {
    rows: [
      "................",
      "......oooo......",
      "....oobbbboo....",
      "...obbsbbsbbo..o",
      "..obbbbsbbsbo.oo",
      ".obbsbbbsbbsbofo",
      "obkbbbsbbbsbbfFo",
      "obbbbbbbsbbbsfFo",
      "owwbbsbbbsbbbfFo",
      "owwwwbbsbbbsbofo",
      ".owwwwwwbbbbo.oo",
      "..oowwwwwwwoo..o",
      "....ooooooo.....",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#8d949c", w: "#d9dde1", f: "#6a7078", F: "#50555c", k: "#101418", s: "#6e757c" },
  },
  // v21 deep water (0076) and v22 Sông Cái (0086)
  ca_leo: {
    rows: [
      "................",
      "........oooo....",
      "....ooooaaaaoo..",
      "..oaaaaasaaaao..",
      ".oaaasaaaaaaoo.o",
      "okaaaaaaaaaaaoto",
      "oaaaaaaaaaaaatTo",
      "owwaaaaaaaaaatTo",
      ".owwwwaaaaaaaoto",
      "..owwwwwaaaaoo.o",
      "...owwwwwwwwo...",
      "....oooooooo....",
      "......oooooo....",
      "................",
      "................",
      "................",
    ],
    pal: { a: "#777b68", s: "#596456", w: "#b8b9aa", t: "#666f5f", T: "#475247", k: "#161b18" },
  },
  ca_bong_tuong: {
    rows: [
      "................",
      "......oooo......",
      "....oobbbboo....",
      "..obbbabbbaoo...",
      ".obbbabbbbbao...",
      "obkbbabBbbbaoooo",
      "obbbabbbbbaatTTo",
      "obbbbbabbbbatTTo",
      "owwbbabbbbbaoooo",
      ".owwbbbabbaaao..",
      "..owwwbbbbboo...",
      "...ooooooooo....",
      ".....o..o.......",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#796448", a: "#a28a61", B: "#514638", w: "#b5a689", t: "#766b50", T: "#504a39", k: "#191914" },
  },
  ca_chien: {
    rows: [
      "................",
      ".......oooo.....",
      "....ooobbbboo...",
      "..oobbbBbbbbbbo.",
      ".obbbBbbbbbbbooo",
      "okbbbbbBBbbbbrro",
      "obbbbBbbbbbbbrRo",
      "obbbbbbbBbbbbrRo",
      "owwbbBBbbbbbbrro",
      ".owwbbbbbbbbbhoo",
      "..owwwbbbbbbbo..",
      "...oooooooooo...",
      "o...o...........",
      ".ooo............",
      "................",
      "................",
    ],
    pal: { b: "#554b3e", B: "#342f29", w: "#a69a80", r: "#675841", R: "#43382d", h: "#86755a", k: "#171714" },
  },
  ca_duoi_song: {
    rows: [
      "................",
      ".....oooo.......",
      "...ooaaaaoo.....",
      "..oaaadadaao....",
      ".oaaadaaadaao...",
      "oakaaadadaaaao..",
      "oaaaadaaadaaaaoo",
      "oaaaadaaadaaaatO",
      "oaaaadaaadaaaaoo",
      ".oaaadaaadaao...",
      "..oaaadadaao....",
      "...oaaaaao......",
      ".....oooo.......",
      "................",
      "................",
      "................",
    ],
    pal: { a: "#927553", d: "#c2a47a", t: "#776046", O: "#4b4235", k: "#242019" },
  },
  ca_tra_dau: {
    rows: [
      "................",
      ".....oooooo.....",
      "...ooaaaassoo...",
      "..oaaaaaaaassoo.",
      ".oaaaaaaaaaaaaoo",
      "oakaasaaaaaaaaff",
      "oaaaaaaaaaaaaafF",
      "oaaaaaaaaaaaaafF",
      "owwaaaaaaaaaaaff",
      ".owwwaaaaaaaaaoo",
      "..owwwwwaaaaao..",
      "...owwwwwwwwo...",
      ".....oooooooo...",
      "................",
      "................",
      "................",
    ],
    pal: { a: "#89979a", s: "#68787b", w: "#c8ced0", f: "#78888b", F: "#56676b", k: "#182024" },
  },
  rua_mai_vang: {
    rows: [
      "................",
      "......oooo......",
      "....ooYYYYoo....",
      "...oYYyyyyYYo...",
      "..oYYyYyyYyYo...",
      ".ohHYYyyyyYYofoo",
      "okhHYYyYYyYYoffo",
      "ohhHYYyyyyYYoffo",
      ".ohHYYyYyyYYofoo",
      "..oYYyyyyYYo....",
      "...oYYYYYYo.....",
      "....ooYYoo......",
      ".....o..o.......",
      "....oo..oo......",
      "................",
      "................",
    ],
    pal: { Y: "#b89b4f", y: "#e0c470", H: "#72804b", h: "#93a16c", f: "#66754b", k: "#1d2117" },
  },
  ca_lang: {
    rows: [
      "................",
      "......oooo......",
      "...oooggggoo....",
      "..ogggggggggo...",
      ".ogggsggggggoooo",
      "okggggggggggorro",
      "ogggggsgggggrRRo",
      "owggggggggggrRRo",
      ".owwggggggggorro",
      "..owwwwgggggoooo",
      "...owwwwwggo....",
      "....oooooooo....",
      "..oo............",
      ".o..............",
      "................",
      "................",
    ],
    pal: { g: "#737c75", s: "#4f605b", w: "#c3c2ad", r: "#d46d3f", R: "#a93e29", k: "#171b19" },
  },
  ca_ngat: {
    rows: [
      "................",
      "....oooo........",
      "..oobbbbooo.....",
      ".obbbbbbbbboo...",
      "okbbbbBbbbbbbo..",
      "obbbbbbbbbbbBboo",
      "owbbbbbbBbbbbbbO",
      ".owwbbbbbbbbbbbo",
      "..owwwbbbbbbboo.",
      "...ooowwbbbbo...",
      "..o...oooooo....",
      ".o..............",
      "o...............",
      "................",
      "................",
      "................",
    ],
    pal: { b: "#383b35", B: "#55594a", w: "#818577", O: "#262b27", k: "#111613" },
  },
  ca_dua: {
    rows: [
      "................",
      ".......oooo.....",
      ".....oossssoo...",
      "...oossssssssoo.",
      "..ossssssssssyoo",
      ".okssssssssssyYo",
      "osssssssssssyYyo",
      "owwsssssssssyYyo",
      ".owwwssssssssyYo",
      "..owwwwssssssyoo",
      "...owwwwwsssoo..",
      ".....oooooooo...",
      "................",
      "................",
      "................",
      "................",
    ],
    pal: { s: "#b9c7c5", w: "#edf0e5", y: "#d6bb68", Y: "#a9904e", k: "#202a28" },
  },
  ca_anh_vu: {
    rows: [
      "................",
      "......oooo......",
      "....ooGGGGoo....",
      "...oGGgGgGGo....",
      "..oGGGgGgGGo.oo.",
      ".oGGgGgGgGGooggo",
      "ookGGGgGgGggGgGo",
      "oGGGGgGgGgGgGgGo",
      "ookGGGgGgGggGgGo",
      ".oGGgGgGgGGooGgo",
      "..oGGGgGgGGo.oo.",
      "...oGGGGGGGo....",
      "....oooooooo....",
      "................",
      "................",
      "................",
    ],
    pal: { G: "#a58e47", g: "#d0b866", k: "#252719" },
  },
  ca_vo_dem: {
    rows: [
      "................",
      "....oooooooo....",
      "...oobbbBbbboo..",
      "..obbbBbbbBbbbo.",
      ".obbbBbbbBbbbboo",
      "okbbbBbbbBbbbsso",
      "obbbbbbBbbbbbsSo",
      "obbbbBbbbbbbbsSo",
      "owwbbbBbbbBbbssO",
      ".owwwbbbbbbbbbso",
      "..owwwwwbbbbooo.",
      "o..owwwwwwwwo...",
      ".oo..oooooooo...",
      "o..o............",
      "................",
      "................",
    ],
    pal: { b: "#505650", B: "#777969", w: "#b6b7a4", s: "#666b62", S: "#454b46", O: "#343b39", k: "#161d1b" },
  },
};

/** Every species' icon: the ones above and Câu cá v3's four (0110, gear-v3.ts). */
export const FISH_ICONS: Record<string, PixelIcon> = { ...BASE_FISH_ICONS, ...FISH_V3_ICONS };
