import type { PixelIcon } from "./icons";

// 16×16 icons for the fishing gear (spec §11): rods, bobbers, baits, the bait boxes, buckets and the fishing kit.
// "." transparent, "o" outline, other letters from the icon's own palette. Original art.

export const GEAR_ICONS: Record<string, PixelIcon> = {
  rod_wood: {
    rows: [
      "..............oo",
      ".............o.l",
      "............o..l",
      "...........rr..l",
      "..........rr...l",
      ".........rr....l",
      "........rr.....l",
      ".......rr......k",
      "......rr........",
      ".....rr.........",
      "..oorr..........",
      ".oyyoo..........",
      ".oyyo...........",
      "..oor...........",
      "...hh...........",
      "..hh............",
    ],
    pal: { r: "#8b5a33", h: "#5a381e", y: "#c9ccd6", l: "#e8e4d8", k: "#9aa0a8" },
  },
  rod_bamboo: {
    rows: [
      "..............oo",
      ".............o.l",
      "............o..l",
      "...........rg..l",
      "..........rr...l",
      ".........gr....l",
      "........rr.....l",
      ".......rg......k",
      "......rr........",
      ".....gr.........",
      "..oorr..........",
      ".oyyoo..........",
      ".oyyo...........",
      "..oor...........",
      "...hh...........",
      "..hh............",
    ],
    pal: { r: "#b7c65a", g: "#6f8a2a", h: "#8a6a28", y: "#c9ccd6", l: "#e8e4d8", k: "#9aa0a8" },
  },
  rod_carbon: {
    rows: [
      "..............oo",
      ".............o.l",
      "............o..l",
      "...........rr..l",
      "..........rr...l",
      ".........rb....l",
      "........rr.....l",
      ".......br......k",
      "......rr........",
      ".....rr.........",
      "..oorr..........",
      ".oyyoo..........",
      ".oyyo...........",
      "..oor...........",
      "...hh...........",
      "..hh............",
    ],
    pal: { r: "#2a2f3a", b: "#3d6fd1", h: "#c0392b", y: "#e8e8ee", l: "#e8e4d8", k: "#9aa0a8" },
  },
  bobber_feather: {
    rows: [
      "................",
      "........o.......",
      ".......owo......",
      "......owwwo.....",
      "......owgwo.....",
      ".....owwgwwo....",
      ".....owwgwwo....",
      ".....owwgwwo....",
      "......owgwo.....",
      "......owgwo.....",
      ".......oro......",
      ".......oro......",
      ".......oro......",
      "........o.......",
      "........o.......",
      "................",
    ],
    pal: { w: "#f4f1ea", g: "#b9ae98", r: "#c0392b" },
  },
  bobber_foam: {
    rows: [
      "................",
      "........o.......",
      ".......oko......",
      ".......oko......",
      "......orrro.....",
      ".....orrrrro....",
      ".....orRrrro....",
      ".....owwwwwo....",
      ".....owwwwwo....",
      "......owwwo.....",
      ".......oko......",
      ".......oko......",
      "........o.......",
      "................",
      "................",
      "................",
    ],
    pal: { r: "#d8433a", R: "#f08a80", w: "#f4f1ea", k: "#5a381e" },
  },
  bobber_lamp: {
    rows: [
      "....l.....l.....",
      ".....l.o.l......",
      ".......y........",
      "...l..oyo..l....",
      ".......y........",
      "......ogo.......",
      ".....orrro......",
      ".....orRro......",
      ".....orrro......",
      ".....owwwo......",
      ".....owwwo......",
      "......owo.......",
      ".......k........",
      ".......k........",
      "................",
      "................",
    ],
    pal: { y: "#ffe08a", l: "#ffd166", g: "#9aa0a8", r: "#d8433a", R: "#f08a80", w: "#f4f1ea", k: "#5a381e" },
  },
  bait_worm: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      "..........oo....",
      ".........oppo...",
      "..oo....oppPo...",
      ".oppo..oppPo....",
      "oppPpooppPo.....",
      "opPPppppPo......",
      ".oPPPppPo.......",
      "..ooPPoo........",
      "....oo..........",
      "................",
      "................",
      "................",
    ],
    pal: { p: "#e98a9a", P: "#c9687a" },
  },
  bait_shrimp: {
    rows: [
      "................",
      "................",
      "................",
      "o...............",
      ".o..ooooo.......",
      "..oopppppoo.....",
      "...opkppppppo...",
      "...opppPpppPpo..",
      "....ooppPpppPpo.",
      "......oopppPppo.",
      "........ooppppo.",
      "..........oooffo",
      ".............ooo",
      "................",
      "................",
      "................",
    ],
    pal: { p: "#f29a6a", P: "#d9774a", k: "#1a1410", f: "#e0662f" },
  },
  bait_bloodworm: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      "....r.....r.....",
      "...r.r...r.r..r.",
      "..r...r.r...rr..",
      "..r....r.....r..",
      ".r..r...r...r...",
      "..rr.r...rrr....",
      "......r.........",
      "...oooooooooo...",
      "...oddddddddo...",
      "....oddddddo....",
      ".....oooooo.....",
      "................",
    ],
    pal: { r: "#c0392b", d: "#8b5a33" },
  },
  bait_box: {
    rows: [
      "................",
      "................",
      "................",
      "..oooooooooooo..",
      "..oLLLLLLLLLLo..",
      ".oLLLLLLLLLLLLo.",
      ".oooooooooooooo.",
      ".obbbbbbbbbbbbo.",
      ".obbbbbkkbbbbbo.",
      ".obbbbbkkbbbbbo.",
      ".obBBBBBBBBBBbo.",
      ".obbbbbbbbbbbbo.",
      ".oooooooooooooo.",
      "................",
      "................",
      "................",
    ],
    pal: { L: "#6fa3dc", b: "#3f7fc4", B: "#2f63a0", k: "#e0b33c" },
  },
  bucket_small: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      ".....oooooo.....",
      "....o......o....",
      "...o........o...",
      "...oooooooooo...",
      "...owwwwwwwwo...",
      "...obbbbbbbbo...",
      "....obbBbbbo....",
      "....obbBbbbo....",
      "....obbbbbbo....",
      ".....oooooo.....",
      "................",
      "................",
    ],
    pal: { w: "#6fb2cf", b: "#d8433a", B: "#a82c26" },
  },
  bucket_large: {
    rows: [
      "................",
      "....oooooooo....",
      "...o........o...",
      "..o..........o..",
      "..o...oo.....o..",
      ".ooooofoooooooo.",
      ".owwwwffwwwwwwo.",
      ".obbbbbbbbbbbbo.",
      "..obbBbbbbbBbo..",
      "..obbBbbbbbBbo..",
      "..obbBbbbbbBbo..",
      "..obbbbbbbbbbo..",
      "...obbbbbbbbo...",
      "...oooooooooo...",
      "................",
      "................",
    ],
    pal: { w: "#6fb2cf", b: "#8d949c", B: "#6a7078", f: "#e0a431" },
  },
  // Hotfix bộ câu cá: Hộp mồi 100 (a two-tier green tackle box, brass clasps), Thùng cá 100 (a slatted wooden crate, a tail
  // over the rim) and the kit (the box and crate together with a rod across).
  bait_box_100: {
    rows: [
      "................",
      "................",
      ".....oooooo.....",
      ".....o....o.....",
      ".oooooooooooooo.",
      ".oLLLLLLLLLLLLo.",
      ".oooooooooooooo.",
      ".ogggggkkgggggo.",
      ".oGGGGGkkGGGGGo.",
      ".oooooooooooooo.",
      ".oggggggggggggo.",
      ".ogggggkkgggggo.",
      ".oGGGGGGGGGGGGo.",
      ".oooooooooooooo.",
      "................",
      "................",
    ],
    pal: { L: "#8fd09b", g: "#5fae6e", G: "#468a53", k: "#e0b33c" },
  },
  bucket_100: {
    rows: [
      "................",
      "................",
      "..........ff....",
      ".........fFf....",
      "..........f.....",
      ".oooooooooooooo.",
      ".owwwwwwwwwwwwo.",
      ".oooooooooooooo.",
      ".obbbbbbbbbbbbo.",
      ".oBBBBBBBBBBBBo.",
      ".oooooooooooooo.",
      ".obbbbbbbbbbbbo.",
      ".oBBBBBBBBBBBBo.",
      ".oooooooooooooo.",
      "..oo........oo..",
      "................",
    ],
    pal: { w: "#6fb2cf", b: "#b7834a", B: "#8b5a33", f: "#e0a431", F: "#b27d16" },
  },
  fishing_kit: {
    rows: [
      "..............oo",
      ".............rr.",
      "............rr..",
      "...........rr...",
      "..........rr....",
      ".........rr.....",
      "oooooooorroooo..",
      "oggggggrrbbbbo..",
      "oggkkgrrbbbbbo..",
      "ogggggrobBBBBo..",
      "ooooorrooooooo..",
      "ogggrrggobbbbo..",
      "oGGrrGGGoBBBBo..",
      "oooooooooooooo..",
      "..hh............",
      ".hh.............",
    ],
    pal: { r: "#8b5a33", h: "#5a381e", g: "#5fae6e", G: "#468a53", k: "#e0b33c", b: "#b7834a", B: "#8b5a33" },
  },
  // v18.2: Cần sợi thủy tinh (a pale green glass-fibre blank with white wraps), Cần thủ (black and gold, a cork grip)
  rod_fiber: {
    rows: [
      "..............oo",
      ".............o.l",
      "............o..l",
      "...........rr..l",
      "..........rw...l",
      ".........rr....l",
      "........wr.....l",
      ".......rr......k",
      "......rw........",
      ".....rr.........",
      "..oorr..........",
      ".oyyoo..........",
      ".oyyo...........",
      "..oor...........",
      "...hh...........",
      "..hh............",
    ],
    pal: { r: "#7fc8a9", w: "#f4f1ea", h: "#2f6f5a", y: "#c9ccd6", l: "#e8e4d8", k: "#9aa0a8" },
  },
  rod_master: {
    rows: [
      "..............oo",
      ".............o.l",
      "............o..l",
      "...........rg..l",
      "..........rr...l",
      ".........gr....l",
      "........rr.....l",
      ".......rg......k",
      "......rr........",
      ".....gr.........",
      "..oorr..........",
      ".oyYoo..........",
      ".oYyo...........",
      "..oog...........",
      "...cc...........",
      "..cc............",
    ],
    pal: { r: "#1a1a22", g: "#e0b33c", y: "#f2d27a", Y: "#b8862a", c: "#c89a5c", l: "#e8e4d8", k: "#9aa0a8" },
  },
  // v18.2 nets: a folded cast net with its lead weights; the big one wider, with a rope coil
  net_small: {
    rows: [
      "................",
      ".......oo.......",
      "......oyyo......",
      ".......oo.......",
      "......onno......",
      ".....on.n.no....",
      ".....onn.nno....",
      "....on.n.n.no...",
      "....onn.n.nno...",
      "...on.n.n.n.no..",
      "...onn.n.n.nno..",
      "..on.n.n.n.n.no.",
      "..olololololol..",
      "...o.o.o.o.o.o..",
      "................",
      "................",
    ],
    pal: { n: "#e8e0c8", y: "#c89a5c", l: "#8d949c" },
  },
  net_big: {
    rows: [
      "......oo........",
      ".....oyyo.......",
      "....oyooyo......",
      ".....oyyo.......",
      ".....onno.......",
      "....on.n.no.....",
      "...onn.n.nno....",
      "..on.n.n.n.no...",
      "..onn.n.n.n.nno.",
      ".on.n.n.n.n.n.no",
      ".onn.n.n.n.n.nno",
      "on.n.n.n.n.n.n.o",
      "olololololololol",
      ".o.o.o.o.o.o.o.o",
      "................",
      "................",
    ],
    pal: { n: "#d8e8f0", y: "#c89a5c", l: "#6a7078" },
  },
  bait_gold: {
    rows: [
      "................",
      "................",
      "......s.........",
      "..........s.....",
      ".....oooooo.....",
      "....oyyyyYYo....",
      "...oyyWyyyYYo...",
      "...oyWyyyyyYo...",
      "...oyyyyyyyYo...",
      "...oYyyyyyYYo...",
      "....oYYYYYYo....",
      ".....oooooo..s..",
      "................",
      ".s..............",
      "................",
      "................",
    ],
    pal: { y: "#f2d27a", Y: "#c9962a", W: "#fff6d0", s: "#ffe08a" },
  },
};
