import type { PixelIcon } from "./icons";

// Câu cá v3 (0110_fishing_v3.sql): 16×16 icons for the parts (hooks, lines, reels), the groundbait bags, the notebook, the
// new buckets and nets, and the four new species. "." transparent, "o" outline, other letters from the icon's own
// palette. Original art; shapes shared within a kind, told apart by colour.

export const GEAR_V3_ICONS: Record<string, PixelIcon> = {
  hook_small: {
    rows: [
      "................",
      "................",
      "......ooo.......",
      "......oeo.......",
      "......ooo.......",
      ".......h........",
      ".......h........",
      ".......h........",
      ".......h........",
      ".......h........",
      "..h....h........",
      "..hh...h........",
      "...h...h........",
      "...hh.hh........",
      "....hhh.........",
      "................",
    ],
    pal: { h: "#c9ccd6", e: "#8d949c" },
  },
  hook_large: {
    rows: [
      "................",
      ".....oooo.......",
      ".....oeeo.......",
      ".....oooo.......",
      "......hH........",
      "......hH........",
      "......hH........",
      "......hH........",
      "......hH........",
      "......hH........",
      ".hh...hH........",
      ".hhH..hH........",
      "..hH..hH........",
      "..hhHhhH........",
      "...hhHH.........",
      "................",
    ],
    pal: { h: "#9aa0a8", H: "#5f656c", e: "#c9ccd6" },
  },
  hook_shrimp: {
    rows: [
      "................",
      "................",
      "......ooo.......",
      "......oeo.......",
      "......ooo.......",
      ".......h........",
      ".......h........",
      ".......h...pp...",
      ".......h..pPPp..",
      ".......h.pPPp...",
      "..h....h..pp....",
      "..hh...h........",
      "...h...h........",
      "...hh.hh........",
      "....hhh.........",
      "................",
    ],
    pal: { h: "#c9ccd6", e: "#8d949c", p: "#e8907a", P: "#c45c48" },
  },
  hook_eel: {
    rows: [
      ".......ooo......",
      ".......oeo......",
      ".......ooo......",
      "........h.......",
      "........h.......",
      "........h.......",
      "........h.......",
      "........h.......",
      "........h.......",
      "........h.......",
      "........h.......",
      "...h....h.......",
      "...hh...h.......",
      "....h...h.......",
      "....hhhhh.......",
      "................",
    ],
    pal: { h: "#b0b5bd", e: "#6a7078" },
  },
  hook_double: {
    rows: [
      "................",
      "................",
      ".......ooo......",
      ".......oeo......",
      ".......ooo......",
      "........h.......",
      "........h.......",
      "........h.......",
      "........h.......",
      ".......hhh......",
      "..h...h...h...h.",
      "..hh..h...h..hh.",
      "...h..h...h..h..",
      "...hhhh...hhhh..",
      "................",
      "................",
    ],
    pal: { h: "#d6d9e0", e: "#8d949c" },
  },
  hook_triple: {
    rows: [
      "................",
      ".......ooo......",
      ".......oeo......",
      ".......ooo......",
      "........H.......",
      "........H.......",
      "........H.......",
      "........H.......",
      ".......HHH......",
      ".h....H.H.H....h",
      ".hh..H..H..H..hh",
      "..h..H..H..H..h.",
      "..hhhH..H..HhhH.",
      "........H.......",
      "......hhH.......",
      "................",
    ],
    pal: { h: "#e0b33c", H: "#9aa0a8", e: "#6a7078" },
  },
  line_02: {
    rows: [
      "................",
      "................",
      "...oooooooooo...",
      "...owwwwwwwwo...",
      "....ollllllo....",
      "....oLLLLLLo....",
      "....ollllllo....",
      "....oLLLLLLo....",
      "....ollllllo....",
      "....oLLLLLLo....",
      "...owwwwwwwwo...",
      "...oooooooooo...",
      ".........l......",
      "..........l.....",
      "...........l....",
      "................",
    ],
    pal: { w: "#8b5a33", l: "#e8e4d8", L: "#c9c2b0" },
  },
  line_03: {
    rows: [
      "................",
      "................",
      "...oooooooooo...",
      "...owwwwwwwwo...",
      "....ollllllo....",
      "....oLLLLLLo....",
      "....ollllllo....",
      "....oLLLLLLo....",
      "....ollllllo....",
      "....oLLLLLLo....",
      "...owwwwwwwwo...",
      "...oooooooooo...",
      ".........l......",
      "..........l.....",
      "...........l....",
      "................",
    ],
    pal: { w: "#3f7fc4", l: "#bfe3f0", L: "#8cc4dc" },
  },
  line_braid: {
    rows: [
      "................",
      "................",
      "...oooooooooo...",
      "...owwwwwwwwo...",
      "....ollllllo....",
      "....oLLLLLLo....",
      "....ollllllo....",
      "....oLLLLLLo....",
      "....ollllllo....",
      "....oLLLLLLo....",
      "...owwwwwwwwo...",
      "...oooooooooo...",
      ".........l......",
      "..........l.....",
      "...........l....",
      "................",
    ],
    pal: { w: "#4a7a2e", l: "#8dc05a", L: "#e0b33c" },
  },
  line_pe: {
    rows: [
      "................",
      "................",
      "...oooooooooo...",
      "...owwwwwwwwo...",
      "....ollllllo....",
      "....oLLLLLLo....",
      "....ollllllo....",
      "....oLLLLLLo....",
      "....ollllllo....",
      "....oLLLLLLo....",
      "...owwwwwwwwo...",
      "...oooooooooo...",
      ".........l......",
      "..........l.....",
      "...........l....",
      "................",
    ],
    pal: { w: "#1a1a22", l: "#e0433a", L: "#f2d27a" },
  },
  reel_1000: {
    rows: [
      "................",
      "................",
      "......oooo......",
      ".....orrrro.....",
      "....orrkkrro....",
      "....orkRRkro....",
      "....orkRRkro.hh.",
      "....orrkkrrohho.",
      ".....orrrro.o...",
      "......oooo......",
      ".......oo.......",
      "......osso......",
      ".....osssso.....",
      "................",
      "................",
      "................",
    ],
    pal: { r: "#8d949c", R: "#c9ccd6", k: "#5f656c", h: "#8b5a33", s: "#6a7078" },
  },
  reel_3000: {
    rows: [
      "................",
      "................",
      "......oooo......",
      ".....orrrro.....",
      "....orrkkrro....",
      "....orkRRkro....",
      "....orkRRkro.hh.",
      "....orrkkrrohho.",
      ".....orrrro.o...",
      "......oooo......",
      ".......oo.......",
      "......osso......",
      ".....osssso.....",
      "................",
      "................",
      "................",
    ],
    pal: { r: "#3f7fc4", R: "#bfe3f0", k: "#2f63a0", h: "#1a1a22", s: "#5f656c" },
  },
  reel_5000: {
    rows: [
      "................",
      "................",
      "......oooo......",
      ".....orrrro.....",
      "....orrkkrro....",
      "....orkRRkro....",
      "....orkRRkro.hh.",
      "....orrkkrrohho.",
      ".....orrrro.o...",
      "......oooo......",
      ".......oo.......",
      "......osso......",
      ".....osssso.....",
      "................",
      "................",
      "................",
    ],
    pal: { r: "#e0b33c", R: "#fff6d0", k: "#b8862a", h: "#1a1a22", s: "#1a1a22" },
  },
  gb_cam: {
    rows: [
      "................",
      "......oooo......",
      ".....ottto......",
      "......oooo......",
      ".....obbbbo.....",
      "....obbbbbbo....",
      "...obbbbbbbbo...",
      "...obbGGGGbbo...",
      "...obGGGGGGbo...",
      "...obbGGGGbbo...",
      "...obbbbbbbbo...",
      "...obbbbbbbbo...",
      "....obbbbbbo....",
      ".....oooooo.....",
      "................",
      "................",
    ],
    pal: { b: "#d9c49a", t: "#8b5a33", G: "#b8a070" },
  },
  gb_tom: {
    rows: [
      "................",
      "......oooo......",
      ".....ottto......",
      "......oooo......",
      ".....obbbbo.....",
      "....obbbbbbo....",
      "...obbbbbbbbo...",
      "...obbGGGGbbo...",
      "...obGGGGGGbo...",
      "...obbGGGGbbo...",
      "...obbbbbbbbo...",
      "...obbbbbbbbo...",
      "....obbbbbbo....",
      ".....oooooo.....",
      "................",
      "................",
    ],
    pal: { b: "#e8b4a0", t: "#8b5a33", G: "#c45c48" },
  },
  gb_thom: {
    rows: [
      "................",
      "......oooo......",
      ".....ottto......",
      "......oooo......",
      ".....obbbbo.....",
      "....obbbbbbo....",
      "...obbbbbbbbo...",
      "...obbGGGGbbo...",
      "...obGGGGGGbo...",
      "...obbGGGGbbo...",
      "...obbbbbbbbo...",
      "...obbbbbbbbo...",
      "....obbbbbbo....",
      ".....oooooo.....",
      "................",
      "................",
    ],
    pal: { b: "#e8e0a0", t: "#4a7a2e", G: "#8dc05a" },
  },
  gb_tanh: {
    rows: [
      "................",
      "......oooo......",
      ".....ottto......",
      "......oooo......",
      ".....obbbbo.....",
      "....obbbbbbo....",
      "...obbbbbbbbo...",
      "...obbGGGGbbo...",
      "...obGGGGGGbo...",
      "...obbGGGGbbo...",
      "...obbbbbbbbo...",
      "...obbbbbbbbo...",
      "....obbbbbbo....",
      ".....oooooo.....",
      "................",
      "................",
    ],
    pal: { b: "#a8b8c0", t: "#3a3a44", G: "#5f7680" },
  },
  fishbook: {
    rows: [
      "................",
      "................",
      "...ooooooooooo..",
      "...occcccccpco..",
      "...ocyyyyyycpo..",
      "...ocyffffycpo..",
      "...ocyyyyyycpo..",
      "...occcccccpco..",
      "...occfffccpco..",
      "...occcccccpco..",
      "...occfffccpco..",
      "...occcccccpco..",
      "...ooooooooooo..",
      "................",
      "................",
      "................",
    ],
    pal: { c: "#8b3a2e", p: "#f0e6c8", y: "#f2d27a", f: "#e0b33c" },
  },
  bucket_medium: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      ".....oooooo.....",
      "....o......o....",
      "...o........o...",
      "...oooooooooo...",
      "...owwwwwwwwo...",
      "...obbbbbbbbo...",
      "....obbBbbbo....",
      "....obbBbbbo....",
      "....obbbbbbo....",
      ".....oooooo.....",
      "................",
      "................",
    ],
    pal: { w: "#6fb2cf", b: "#3f8c4a", B: "#2c6634" },
  },
  bucket_foam: {
    rows: [
      "................",
      "................",
      "................",
      "..oooooooooooo..",
      "..oLLLLLLLLLLo..",
      ".oooooooooooooo.",
      ".obbbbbbbbbbbbo.",
      ".obbbbbbbbbbbbo.",
      ".obBBBBBBBBBBbo.",
      ".obbbbbbbbbbbbo.",
      ".obbbbbbbbbbbbo.",
      ".obBBBBBBBBBBbo.",
      ".oooooooooooooo.",
      "................",
      "................",
      "................",
    ],
    pal: { L: "#ffffff", b: "#eef0f2", B: "#c9ccd6" },
  },
  bucket_ice: {
    rows: [
      "................",
      "................",
      "................",
      "..oooooooooooo..",
      "..oLLLLLLLLLLo..",
      ".oooooooooooooo.",
      ".obbbbbbbbbbbbo.",
      ".obbbbbbbbbbbbo.",
      ".obBBBBBBBBBBbo.",
      ".obbbbbbbbbbbbo.",
      ".obbbbbbbbbbbbo.",
      ".obBBBBBBBBBBbo.",
      ".oooooooooooooo.",
      "................",
      "................",
      "................",
    ],
    pal: { L: "#e8f4fa", b: "#3f7fc4", B: "#2f63a0" },
  },
  net_gill: {
    rows: [
      "......oo........",
      ".....oyyo.......",
      "....oyooyo......",
      ".....oyyo.......",
      ".....onno.......",
      "....on.n.no.....",
      "...onn.n.nno....",
      "..on.n.n.n.no...",
      "..onn.n.n.n.nno.",
      ".on.n.n.n.n.n.no",
      ".onn.n.n.n.n.nno",
      "on.n.n.n.n.n.n.o",
      "olololololololol",
      ".o.o.o.o.o.o.o.o",
      "................",
      "................",
    ],
    pal: { n: "#e0d08a", y: "#8b5a33", l: "#8d949c" },
  },
  net_cast: {
    rows: [
      "......oo........",
      ".....oyyo.......",
      "....oyooyo......",
      ".....oyyo.......",
      ".....onno.......",
      "....on.n.no.....",
      "...onn.n.nno....",
      "..on.n.n.n.no...",
      "..onn.n.n.n.nno.",
      ".on.n.n.n.n.n.no",
      ".onn.n.n.n.n.nno",
      "on.n.n.n.n.n.n.o",
      "olololololololol",
      ".o.o.o.o.o.o.o.o",
      "................",
      "................",
    ],
    pal: { n: "#bfe3f0", y: "#e0b33c", l: "#5f656c" },
  },
};

export const FISH_V3_ICONS: Record<string, PixelIcon> = {
  luon_dong: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      "..........ooo...",
      ".........obbbo..",
      "........obbkbbo.",
      ".oo....obbbbbo..",
      "obbo..obbbbwo...",
      "obbbooobbbwo....",
      ".obbbbbbbwwo....",
      "..obbbbwwwo.....",
      "...oowwwoo......",
      ".....ooo........",
      "................",
      "................",
    ],
    pal: { b: "#8a6a28", w: "#c9a860", k: "#1a1410" },
  },
  ca_chinh: {
    rows: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "..............oo",
      "oo..........oobo",
      "obo......ooobbbo",
      ".obo...oobbsbbko",
      ".obboooobsbbbbwo",
      "..obbbbbbbbbwwo.",
      "...obsbbbbwwoo..",
      "....oowwwwoo....",
      "......oooo......",
      "................",
      "................",
    ],
    pal: { b: "#5a5a3a", w: "#b8b890", s: "#2f2f1e", k: "#1a1410" },
  },
  ba_ba: {
    rows: [
      "................",
      "................",
      "................",
      ".....oooooo.....",
      "...oossssssoo...",
      "..ossSssssSsso..",
      ".osssssSSsssssoo",
      "osSsssSSSSsssSok",
      "osssssSSSSssssok",
      ".osssssSSsssssoo",
      "..ossSssssSsso..",
      "...oossssssoo...",
      "..oo.oooooo.oo..",
      "..ll........ll..",
      "................",
      "................",
    ],
    pal: { s: "#7d8a3c", S: "#5f6b2a", k: "#9aa05a", l: "#9aa05a" },
  },
  ca_tai_tuong: {
    rows: [
      "................",
      ".......ooo......",
      ".....oobbboo....",
      "....obbbbbbbo...",
      "...obbbbbbbbbo..",
      "..obkbbbbbbbbbo.",
      "..obbbbbsbbbbbfo",
      ".owbbbbbsbbbbbfo",
      ".owwbbbbsbbbbbfo",
      "..owwbbbbbbbbbfo",
      "..owwwwbbbbbbbo.",
      "...owwwwwwbbbo..",
      "....oowwwwwoo...",
      "......ooooo.....",
      "................",
      "................",
    ],
    pal: { b: "#b0a88a", w: "#e8e0c8", s: "#6a624a", k: "#1a1410", f: "#8a826a" },
  },
};
