import type { HairStyle } from "@/lib/game/types";
import { R, type Dir3, type Layer } from "./layers";

// Hair layers, drawn over the bald head. Codes: . transparent · o line · h hair · H highlight · d shade.
// No outer outline in the art: compose.ts traces one around the hair (over the face too, which draws the bangs' edge).
// Rows from ROW.lag (16) down are the tips: they lag a pixel behind the head while walking. In the front view the rows
// from 21 down fall behind the body (drawn only where nothing else is). Every style covers the scalp (tested).

const BANGS_TOP = [
  R(8, "hhhhhhhh"),
  R(6, "hhhhHHhhhhhh"),
  R(4, "hhhHHHhhhhhhhhhh"),
  R(3, "hhHHhhhhhhhhhhhhhd"),
  R(2, "hhHhhhhhhhhhhhhhhhdd"),
  R(2, "hhhhhhhhhhhhhhhhhhdd"),
  R(2, "hhhhhhhdhhhhhhhhhhdd"),
  R(2, "hhhhhhdhhhhhhdhhhhdd"),
  R(2, "hhhhhdhhhhhhdhhhhhdd"),
  R(2, "hhhh.hhhhh.hhhh.hhdd"),
  R(2, "hhh..h....h....h.hhd"),
];
const SIDE_TOP = [
  R(8, "hhhhhhhh"),
  R(6, "hhhhHHhhhhhhh"),
  R(4, "hhhHHHhhhhhhhhhhh"),
  R(3, "hhHHhhhhhhhhhhhhhhd"),
  R(3, "hHhhhhhhhhhhhhhhhhdd"),
  R(3, "hhhhhhhhhhhhhhhhhhdd"),
  R(3, "hhhhhhdhhhhhhhhhhhdd"),
  R(3, "hhhhhdhhhhhhhhhhhhdd"),
  R(3, "hhhh.hhhhhhhhhhhhhdd"),
  R(3, "hh..h..hhhhhhhhhhhdd"),
];
const BACK_TOP = [
  R(8, "hhhhhhhh"),
  R(6, "hhhhHHhhhhhh"),
  R(4, "hhhHHHhhhhhhhhhh"),
  R(3, "hhHHhhhhhhhhhhhhhd"),
];
const backFall = (n: number) =>
  Array.from({ length: n }, (_, i) => R(2, i % 3 === 0 ? "hhhhdhhhhhhhdhhhhhdd" : i % 3 === 1 ? "hhhhhhdhhhhhhhdhhhdd" : "hhhhhhhhhhhhhhhhhhdd"));

const BASE_HAIR: Record<"short" | "bob" | "long", Record<Dir3, Layer>> = {
  // nam: short and spiky, with pointed bangs and sideburns
  short: {
    down: { top: 2, rows: [
      R(8, "hh..hhh..h"),
      R(6, "hhhhhHhhhhhhd"),
      R(4, "hhhhHHhhhhhhhhhd"),
      R(3, "hhhHHhhhhhhhhhhhdd"),
      R(3, "hhHhhhhhhhhhhhhhdd"),
      R(2, "hhhhhhhhhhhhhhhhhhdd"),
      R(2, "hhhhdhhhhhdhhhhhhhdd"),
      R(2, "hhhhhdhhhhhdhhhhhdhd"),
      R(2, "hhhh.hhhh.hhhh.hhhdd"),
      R(2, "hhh..hh...hh...hh.dd"),
      R(2, "hh................dd"),
      R(3, "h................d"),
    ] },
    left: { top: 2, rows: [
      R(9, "hh..hhh..hh"),
      R(6, "hhhhhHhhhhhhhhh"),
      R(4, "hhhhHHhhhhhhhhhhhh"),
      R(3, "hhhHHhhhhhhhhhhhhhhd"),
      R(3, "hhHhhhhhhhhhhhhhhhdd"),
      R(3, "hhhhhhhhhhhhhhhhhhd"),
      R(3, "hhhhdhhhhhhhhhhhhdd"),
      R(3, "hh.hhh.hhhhhhhhhhdd"),
      R(3, "h...h..hhhhhhhhhhdd"),
      R(10, "hhhhhhhhhdd"),
      R(10, "hhhhhhhhhhd"),
      R(11, "h..hhhhhhd"),
      R(11, "h..hhhhhhd"),
      R(14, "hhhhhd"),
      R(14, "hhhhd"),
      R(15, "h.h"),
    ] },
    up: { top: 2, rows: [
      R(8, "hh..hhh..h"),
      R(6, "hhhhhHhhhhhhd"),
      R(4, "hhhhHHhhhhhhhhhd"),
      R(3, "hhhHHhhhhhhhhhhhdd"),
      R(3, "hhHhhhhhhhhhhhhhdd"),
      ...backFall(9),
      R(3, "hhhhhhhhhhhhhhhhdd"),
      R(4, "hhdhhhhdhhhhhdhd"),
      R(5, "hh.hhh.hhh.hhd"),
    ] },
  },
  // shoulder length: a rounded bob with straight bangs and curtains that curl in at the jaw
  bob: {
    down: { top: 1, rows: [
      ...BANGS_TOP,
      R(2, "hhh..............hhd"),
      R(2, "hHh..............hhd"),
      R(2, "hHh..............hhd"),
      R(2, "hhh..............hhd"),
      R(2, "hhh..............hdd"),
      R(2, "hhh..............hdd"),
      R(2, "hhhh............hhhd"),
      R(2, "hhhd............dhhd"),
      R(3, "hd..............dh"),
    ] },
    left: { top: 1, rows: [
      ...SIDE_TOP,
      R(3, "h...h..hhhhhhhhhhhdd"),
      R(10, "hhhhhhhhhhdd"),
      R(10, "hhhhhhhhhhdd"),
      R(10, "hHhhhhhhhhdd"),
      R(10, "hHhhhdhhhhdd"),
      R(10, "hhhhhhhdhhdd"),
      R(10, "hhhhdhhhhhdd"),
      R(10, "hhhhhhhhhhhd"),
      R(11, "hhhhhhhhhd"),
      R(12, "dhhhhhhd"),
    ] },
    up: { top: 1, rows: [
      ...BACK_TOP,
      ...backFall(15),
      R(2, "hhhdhhhhhhhdhhhhhhdd"),
      R(3, "dhhdhhhhhhhdhhhhdd"),
    ] },
  },
  // long: the bob's crown with locks falling past the shoulders to the waist
  long: {
    down: { top: 1, rows: [
      ...BANGS_TOP,
      R(2, "hhh..............hhd"),
      R(2, "hHh..............hhd"),
      R(2, "hHh..............hhd"),
      R(2, "hhh..............hhd"),
      R(2, "hHh..............hdd"),
      R(2, "hhh..............hdd"),
      R(2, "hhh..............hhd"),
      R(2, "hhhh............hhhd"),
      R(1, "hhhh..............hhhd"),
      ...Array.from({ length: 7 }, (_, i) => R(1, (i % 2 ? "hHhd" : "hhhd") + ".............." + "dhhd")),
      R(1, "hhd................dhd"),
      R(2, "h..................h"),
    ] },
    left: { top: 1, rows: [
      ...SIDE_TOP,
      R(3, "h...h..hhhhhhhhhhhdd"),
      R(10, "hhhhhhhhhhdd"),
      R(10, "hhhhhhhhhhdd"),
      R(10, "hHhhhhhhhhdd"),
      R(10, "hHhhhdhhhhdd"),
      R(10, "hhhhhhhdhhdd"),
      R(11, "hhhdhhhhhdd"),
      R(12, "hhhhhhhhdd"),
      R(13, "hhhhhhhdd"),
      ...Array.from({ length: 8 }, (_, i) => R(14, i % 3 === 1 ? "hHhhdd" : "hhhhdd")),
      R(14, "hhhdd"),
      R(15, "hd"),
    ] },
    up: { top: 1, rows: [
      ...BACK_TOP,
      ...backFall(16),
      ...Array.from({ length: 8 }, (_, i) => R(3, i % 2 ? "hhhdhhhhhhhdhhhhdd" : "hhhhhhdhhhhhhhdhdd")),
      R(4, "hdhhhdhhhdhhhhd"),
      R(5, "h...h...h...h"),
    ] },
  },
};

/** A speckled run of `n` pixels (buzz cut texture). */
const speck = (n: number, seed: number) => Array.from({ length: n }, (_, i) => ((i * 3 + seed * 2) % 5 === 0 ? "d" : "h")).join("");
/** A symmetric row from its left half (12 columns). */
const sym = (half: string): string => half + [...half].reverse().join("");

// sleek hair pulled back (ponytail, bun, braids): crown rows 3–8, the forehead left open under a side part
const SLEEK_DOWN = [
  R(8, "hhhhhhhh"),
  R(6, "hhhhHHhhhhhh"),
  R(5, "hhhHHhhhhhhhhd"),
  R(4, "hhHhhhhhhhhhhhhd"),
  R(4, "hhhhhhhhhhhhhhdd"),
  R(4, "hhhhhhhdhhhhhhhd"),
  R(4, "hhhhhh...hhhhhhd"),
  R(4, "hhh.........hhhd"),
];
const SLEEK_LEFT = [
  R(8, "hhhhhhhh"),
  R(6, "hhhhHHhhhhhh"),
  R(5, "hhhHHhhhhhhhhd"),
  R(4, "hhHhhhhhhhhhhhhd"),
  R(4, "hhhhhhhhhhhhhhdd"),
];
const SLEEK_UP = [
  R(8, "hhhhhhhh"),
  R(6, "hhhhHHhhhhhh"),
  R(5, "hhhHHhhhhhhhhd"),
  R(4, "hhHhhhhdhhhhhhhd"),
  R(4, "hhhhdhhhhhhdhhhd"),
  R(4, "hhhhhdhhhhdhhhhd"),
];
const CURLY_CROWN = [
  sym("......hh.hhh"),
  sym("....hhhhhHhh"),
  sym("...hhhdhhHHh"),
  sym("..hhhhhhdhhh"),
  sym("..hdhhhhhhhd"),
  sym(".hhhhdhhhhhh"),
  sym(".hhdhhhhhdhh"),
  sym("..hhhhhdhhhh"),
];

const NEW_HAIR: Record<"buzz" | "undercut" | "curly" | "ponytail" | "twin_braids" | "bun" | "bangs", Record<Dir3, Layer>> = {
  // a buzz cut: a speckled shell close to the scalp, straight hairline
  buzz: {
    down: { top: 4, rows: [
      R(7, speck(10, 0)), R(5, speck(14, 1)), R(4, speck(16, 2)), R(4, speck(16, 3)), R(4, speck(16, 4)),
      R(4, "hd............dh"), R(4, "h..............h"),
    ] },
    left: { top: 4, rows: [
      R(7, speck(11, 0)), R(5, speck(14, 1)), R(4, speck(16, 2)), R(4, speck(16, 3)), R(4, speck(16, 4)),
      R(9, speck(11, 0)), R(10, speck(10, 1)), R(11, speck(9, 2)), R(12, speck(8, 3)), R(13, speck(7, 4)),
      R(14, speck(6, 0)), R(14, speck(6, 1)),
    ] },
    up: { top: 4, rows: [
      R(7, speck(10, 0)), R(5, speck(14, 1)),
      ...Array.from({ length: 10 }, (_, i) => R(4, speck(16, i + 2))),
      R(5, "h.h.h.h.h.h.h."),
    ] },
  },
  // an undercut: shaved sides (shade) under a long top swept over to one side
  undercut: {
    down: { top: 1, rows: [
      R(9, "hhHHhh"),
      R(6, "hhhhhHHhhhh"),
      R(5, "hhhhhhHHhhhhhh"),
      R(4, "hhhhhhhhHhhhhhhh"),
      R(4, "dhhhhhhhhHhhhhhd"),
      R(4, "ddhhhhhhhhhhhhdd"),
      R(4, "ddhhhhhhhhhhhhdd"),
      R(4, "ddhhhhhhhhhhhhdd"),
      R(4, "dd.....hhhhhhhdd"),
      R(4, "d.........hhhh.d"),
      R(4, "d..............d"),
    ] },
    left: { top: 1, rows: [
      R(9, "hhHHhhh"),
      R(6, "hhhhHHhhhhh"),
      R(4, "hhhhhhHHhhhhhh"),
      R(3, "hhhhhhhhhHhhhhhd"),
      R(3, "hhhhhhhhhhhhhhhdd"),
      R(3, "hhhhhhhhhhhhhdddd"),
      R(3, "hhhhhhhhhhhhddddd"),
      R(4, "hhhhhhhhhhhddddd"),
      R(4, "h...hhhhdddddddd"),
      R(10, "dddddddddd"),
      R(11, "ddddddddd"),
      R(12, "dddddddd"),
      R(13, "ddddddd"),
      R(14, "dddddd"),
      R(14, "dddddd"),
    ] },
    up: { top: 1, rows: [
      R(9, "hhHHhh"),
      R(6, "hhhhhHHhhhh"),
      R(5, "hhhhhhHHhhhhhh"),
      R(4, "hhhhhhhhHhhhhhhh"),
      R(4, "hhhhhhhhhhhhhhhh"),
      R(4, "hhhhhhhhhhhhhhhh"),
      R(4, "hhhhhhhhhhhhhhhd"),
      R(4, "hdhhdhhhhdhhhdhd"),
      ...Array.from({ length: 7 }, () => R(4, "dddddddddddddddd")),
      R(5, "d.d.d.d.d.d.d."),
    ] },
  },
  // a big curly mop: bumpy outline all round, curls down the sides
  curly: {
    down: { top: 1, rows: [
      ...CURLY_CROWN,
      sym(".hhhh.hh.hh."),
      sym(".hhh..h....."),
      sym("..hhh......."),
      sym(".hhdh......."),
      sym("..hhh......."),
      sym(".hhd........"),
      sym("..h........."),
    ] },
    left: { top: 1, rows: [
      ...CURLY_CROWN,
      ".hh.h..hhhhhhhhhhhhhhh..",
      "..h......hhhhhhdhhhhhh..",
      ".........hhdhhhhhhhhhh..",
      "..........hhhhhdhhhhhhh.",
      "...........hhhhhhhdhhh..",
      "............hhdhhhhhhhh.",
      "............hhhhhhdhhh..",
      "..............hh.hhh.h..",
    ] },
    up: { top: 1, rows: [
      ...CURLY_CROWN,
      sym(".hhhdhhhhhhh"),
      sym("..hhhhhdhhhh"),
      sym(".hhdhhhhhhhd"),
      sym("..hhhhdhhhhh"),
      sym(".hhhhhhhhdhh"),
      sym("..hdhhhhhhhh"),
      sym(".hhhhhdhhhhh"),
      sym("..hh.hhh.hhh"),
    ] },
  },
  // a ponytail: sleek crown, a band at the back and a tail swinging behind
  ponytail: {
    down: { top: 3, rows: [
      ...SLEEK_DOWN,
      R(4, "hh............hdhd"),
      R(4, "h..............dhd"),
      ...Array.from({ length: 6 }, (_, i) => R(20, i % 2 ? "Hd" : "hd")),
      R(20, "d"),
    ] },
    left: { top: 3, rows: [
      ...SLEEK_LEFT,
      R(4, "hhhhhhhhhhhhhhhdo"),
      R(4, "hh...hhhhhhhhhhdoh"),
      R(9, "hhhhhhhhhhdhh"),
      R(10, "hhhhhhhhhdhHd"),
      R(11, "hhhhhhhhdhHd"),
      R(12, "hhhhhhhdhhd"),
      R(14, "hhhhhdhhd"),
      R(14, "hhhhdhhhd"),
      R(19, "hhd"),
      R(19, "hHd"),
      R(19, "hhd"),
      R(19, "hd"),
      R(19, "hd"),
      R(20, "d"),
    ] },
    up: { top: 3, rows: [
      ...SLEEK_UP,
      R(4, "hhhhhhdhhdhhhhhd"),
      R(4, "hhhhhhoooohhhhhd"),
      R(4, "hhhhhhhHhhhhhhhd"),
      R(4, "hhhhhhhHhhhhhhhd"),
      R(4, "hhhhhhdHhdhhhhhd"),
      R(4, "hhhhhhhHhhhhhhhd"),
      R(4, "hhhhhhhHhhhhhhhd"),
      R(10, "hhhd"),
      R(10, "hHhd"),
      R(10, "hHhd"),
      R(10, "hhhd"),
      R(10, "hHhd"),
      R(11, "hhd"),
      R(11, "hHd"),
      R(11, "hd"),
    ] },
  },
  // two plaited braids from a centre part, each tied off with a band and a tuft
  twin_braids: {
    down: { top: 3, rows: [
      R(8, "hhhhhhhh"),
      R(6, "hhhhhdhhhhhh"),
      R(5, "hhhHHhdhhHHhhd"),
      R(4, "hhhHhhhdhhhHhhhd"),
      R(4, "hhhhhhhdhhhhhhhd"),
      R(4, "hhhhhhhdhhhhhhhd"),
      R(4, "hhhhhhh..hhhhhhd"),
      R(4, "hhhh........hhhd"),
      R(4, "hh............hd"),
      "..hhh..............hhd..",
      "..hHh..............hHd..",
      "..dhd..............dhd..",
      "..hHh..............hHd..",
      "..dhd..............dhd..",
      "..hHh..............hHd..",
      "..dhd..............dhd..",
      "..ooo..............ooo..",
      "..hhh..............hhd..",
      "...h................h...",
    ] },
    left: { top: 3, rows: [
      ...SLEEK_LEFT,
      R(4, "hhhhhhhhhhhhhhhd"),
      R(4, "hh...hhhhhhhhhhd"),
      R(9, "hhhhhhhhhhd"),
      R(10, "hhhhhhhhhd"),
      R(11, "hhhhhhhhd"),
      R(12, "hhhhhhhd"),
      R(13, "hHhhhhd"),
      R(13, "dhdhhhd"),
      R(13, "hHh"),
      R(13, "dhd"),
      R(13, "hHh"),
      R(13, "dhd"),
      R(13, "ooo"),
      R(13, "hhh"),
      R(14, "h"),
    ] },
    up: { top: 3, rows: [
      R(8, "hhhhhhhh"),
      R(6, "hhhhhdhhhhhh"),
      R(5, "hhhHHhdhhHHhhd"),
      ...Array.from({ length: 10 }, (_, i) => R(4, i % 2 ? "hhhhhhhdhhhhhhhd" : "hhHhhhhdhhhHhhhd")),
      "...hhh............hhd...",
      "...hHh............hHd...",
      "...dhd............dhd...",
      "...hHh............hHd...",
      "...dhd............dhd...",
      "...ooo............ooo...",
      "...hhh............hhd...",
      "....h..............h....",
    ] },
  },
  // a bun: sleek hair drawn up into a round knot on the crown
  bun: {
    down: { top: 1, rows: [
      R(10, "hhhh"),
      R(9, "hHHhhd"),
      R(9, "hhhhdd"),
      R(6, "hhhhoooohhhh"),
      ...SLEEK_DOWN.slice(2),
      R(4, "hh............hd"),
    ] },
    left: { top: 1, rows: [
      R(11, "hhhh"),
      R(10, "hHHhhd"),
      R(10, "hhhhdd"),
      R(6, "hhhhhoooohhh"),
      ...SLEEK_LEFT.slice(2),
      R(4, "hhhhhhhhhhhhhhhd"),
      R(4, "hh...hhhhhhhhhhd"),
      R(9, "hhhhhhhhhhd"),
      R(10, "hhhhhhhhhd"),
      R(11, "hhhhhhhhd"),
      R(12, "hhhhhhhd"),
      R(13, "hhhhhhd"),
      R(14, "hhhhhd"),
      R(14, "hhhhd"),
    ] },
    up: { top: 1, rows: [
      R(10, "hhhh"),
      R(9, "hHHhhd"),
      R(9, "hhhhdd"),
      R(6, "hhhhoooohhhh"),
      R(5, "hhhhhdhdhhhhhd"),
      ...Array.from({ length: 10 }, (_, i) => R(4, i % 2 ? "hhhhhdhhdhhhhhhd" : "hhhhdhhhhdhhhhhd")),
      R(5, "hh.h.hh.h.hhh"),
    ] },
  },
  // blunt bangs: a straight fringe to the brows and straight sides to the jaw
  bangs: {
    down: { top: 1, rows: [
      ...BANGS_TOP.slice(0, 7),
      R(2, "hhhhhhhhhhhhhhhhhhdd"),
      R(2, "hhhhhhhhhhhhhhhhhhdd"),
      R(2, "hHhhhhhhhhhhhhhhhhdd"),
      R(2, "hhdddddddddddddddhdd"),
      ...Array.from({ length: 6 }, (_, i) => R(2, i % 3 === 1 ? "hHh..............hdd" : "hhh..............hdd")),
      R(2, "ddd..............ddd"),
    ] },
    left: { top: 1, rows: [
      ...SIDE_TOP.slice(0, 7),
      R(3, "hhhhhhhhhhhhhhhhhhd"),
      R(3, "hhhhhhhhhhhhhhhhhhd"),
      R(3, "hhhhhhhhhhhhhhhhhhd"),
      R(3, "dddddddhhhhhhhhhhhd"),
      R(10, "hhhhhhhhhhd"),
      R(10, "hHhhhhhhhhd"),
      R(10, "hHhhhdhhhhd"),
      R(10, "hhhhhhhdhhd"),
      R(10, "hhhhhhhhhhd"),
      R(10, "hhhhhhhhhhd"),
      R(10, "dddddddddd"),
    ] },
    up: { top: 1, rows: [
      ...BACK_TOP,
      ...backFall(13),
      R(2, "dddddddddddddddddddd"),
    ] },
  },
};

export const HAIR: Record<HairStyle, Record<Dir3, Layer>> = { ...BASE_HAIR, ...NEW_HAIR };

/** Styles with loose ends that lag a pixel behind the head while walking. */
export const SWAYING_HAIR: ReadonlySet<HairStyle> = new Set<HairStyle>(["long", "ponytail", "twin_braids"]);

export const HAIR_CODES = ".ohHd";
