import type { HairStyle } from "@/lib/game/types";
import type { Dir3, Layer } from "./layers";

// Hair layers (codes: . transparent · o outline · h hair · H highlight). Drawn over the bald head;
// every style covers the scalp (checked by tests/unit/game-art.test.ts).
export const HAIR: Record<HairStyle, Record<Dir3, Layer>> = {
  short: {
    down: { top: 3, rows: [
      "........oooooooo........",
      "......oohhhhhhhhoo......",
      ".....ohhhhHHhhhhhho.....",
      ".....ohhhHHhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhh.hhhh.hhho.....",
      "......h..........h......",
      "......h..........h......",
      "......h..........h......",
      "......h..........h......",
      "......h..........h......",
    ] },
    left: { top: 3, rows: [
      "........oooooooo........",
      "......oohhhhhhhhoo......",
      ".....ohhhhhHHhhhhho.....",
      ".....ohhhhHHhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      "......ohh...hhhhhho.....",
      "............hhhhhh......",
      "............hhhhhh......",
      "............hhhhhh......",
      "............hhhhhh......",
      "............hhhhhh......",
      "............hhhh........",
    ] },
    up: { top: 3, rows: [
      "........oooooooo........",
      "......oohhhhhhhhoo......",
      ".....ohhhhHHhhhhhho.....",
      ".....ohhhHHhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhHhhhhhho.....",
      ".....ohhhhHhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".......ohhhhhhhho.......",
    ] },
  },
  bob: {
    down: { top: 3, rows: [
      "........oooooooo........",
      "......oohhhhhhhhoo......",
      ".....ohhhhHHhhhhhho.....",
      ".....ohhhHHhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....oooo........oooo....",
    ] },
    left: { top: 3, rows: [
      "........oooooooo........",
      "......oohhhhhhhhoo......",
      ".....ohhhhhHHhhhhho.....",
      ".....ohhhhHHhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      "......ohhhhhhhhhhhho....",
      "............hhhhhhho....",
      "............hhhhhhho....",
      "............hhhhhhho....",
      "............hhhhhhho....",
      "............hhhhhhho....",
      "............hhhhhhho....",
      "...........hhhhhhhho....",
      "...........oooooooo.....",
    ] },
    up: { top: 3, rows: [
      "........oooooooo........",
      "......oohhhhhhhhoo......",
      ".....ohhhhHHhhhhhho.....",
      ".....ohhhHHhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhHhhhhhho.....",
      ".....ohhhhHhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      "....ohhhhhhhhhhhhhho....",
      "....ohhhhhhhhhhhhhho....",
      "....oooooooooooooooo....",
    ] },
  },
  long: {
    down: { top: 3, rows: [
      "........oooooooo........",
      "......oohhhhhhhhoo......",
      ".....ohhhhHHhhhhhho.....",
      ".....ohhhHHhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "....ohh..........hho....",
      "...ohhh..........hhho...",
      "...ohhh..........hhho...",
      "...ohhh..........hhho...",
      "...ohhh..........hhho...",
      "...ohhh..........hhho...",
      "...oooo..........oooo...",
    ] },
    left: { top: 3, rows: [
      "........oooooooo........",
      "......oohhhhhhhhoo......",
      ".....ohhhhhHHhhhhho.....",
      ".....ohhhhHHhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      "......ohhhhhhhhhhhho....",
      "............hhhhhhho....",
      "............hhhhhhho....",
      "............hhhhhhho....",
      "............hhhhhhho....",
      "............hhhhhhho....",
      "............hhhhhhho....",
      "...........hhhhhhhho....",
      ".............hhhhho.....",
      ".............hhhhho.....",
      ".............hhhhho.....",
      ".............hhhhho.....",
      ".............hhhhho.....",
      ".............hhhhho.....",
      ".............hhhhho.....",
      ".............hhhhho.....",
      ".............hhhhho.....",
      ".............hhhhho.....",
      ".............oooooo.....",
    ] },
    up: { top: 3, rows: [
      "........oooooooo........",
      "......oohhhhhhhhoo......",
      ".....ohhhhHHhhhhhho.....",
      ".....ohhhHHhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhHhhhhhho.....",
      ".....ohhhhHhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....ohhhhhhhhhhhho.....",
      ".....oooooooooooooo.....",
    ] },
  },
};

export const HAIR_CODES = ".ohH";
