import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { FOREST_GRID } from "@/lib/game/world/forest-grid.data";
import {
  computeForestGrid, FOREST_CELL, FOREST_COLS, FOREST_ROWS, forestAt, forestCore, inForest, nearForest,
} from "@/lib/game/world/forest-grid";
import { inTramForest } from "@/lib/game/world/scenery";

const MIGRATION = join(process.cwd(), "supabase/migrations/0096_forest_professions.sql");

describe("the forest grid (server's rừng tràm)", () => {
  const live = computeForestGrid();

  if (process.env.WRITE_FOREST_GRID === "1") {
    writeFileSync(join(process.cwd(), "lib/game/world/forest-grid.data.ts"),
      "// GENERATED by WRITE_FOREST_GRID=1 vitest tests/unit/forest-grid.test.ts (lib/game/world/forest-grid.ts) — do not edit.\n"
      + "export const FOREST_GRID: readonly string[] = [\n" + live.map((r) => `  "${r}",`).join("\n") + "\n];\n");
    console.log(live.map((r, i) => `(${i}, '${r}')`).join(",\n"));
  }

  it("is the scenery's forest, cell centre by cell centre", () => {
    expect(FOREST_GRID).toEqual(live);
    expect(FOREST_GRID).toHaveLength(FOREST_ROWS);
    for (const r of FOREST_GRID) expect(r).toHaveLength(FOREST_COLS);
  });

  it("is seeded into the migration row for row", () => {
    const sql = readFileSync(MIGRATION, "utf8");
    const rows = [...sql.matchAll(/^\s*\((\d+), '([01]+)'\)[,;]?\s*$/gm)].map((m) => ({ cy: Number(m[1]), bits: m[2] }));
    expect(rows.map((r) => r.cy)).toEqual(FOREST_GRID.map((_, i) => i));
    expect(rows.map((r) => r.bits)).toEqual([...FOREST_GRID]);
  });

  it("has real forest, with core cells to spawn animals on", () => {
    let forest = 0, core = 0;
    for (let cy = 0; cy < FOREST_ROWS; cy++) for (let cx = 0; cx < FOREST_COLS; cx++) {
      if (forestAt(cx, cy)) forest++;
      if (forestCore(cx, cy)) core++;
    }
    expect(forest).toBeGreaterThan(40);
    expect(core).toBeGreaterThan(8);
  });

  it("answers points like the server: in (the cell), near (a neighbour too), nothing off the world", () => {
    let checked = 0;
    for (let cy = 1; cy < FOREST_ROWS - 1 && checked < 20; cy++) for (let cx = 1; cx < FOREST_COLS - 1 && checked < 20; cx++) {
      if (!forestCore(cx, cy)) continue;
      const x = (cx + 0.5) * FOREST_CELL, y = (cy + 0.5) * FOREST_CELL;
      expect(inForest(x, y)).toBe(true);
      expect(inTramForest(x, y)).toBe(true);
      expect(nearForest(x + FOREST_CELL, y)).toBe(true);
      checked++;
    }
    expect(checked).toBeGreaterThan(0);
    expect(inForest(-10, -10)).toBe(false);
    expect(nearForest(-200, -200)).toBe(false);
    expect(forestAt(FOREST_COLS, 0)).toBe(false);
  });
});
